USE kimeraso_LaChilenita;
INSERT INTO roles VALUES (1, 'admin', 'Administrador');
INSERT INTO roles VALUES (2, 'supervisor', 'Supervisor');
INSERT INTO roles VALUES (3, 'employee', 'Empleado');
INSERT INTO roles VALUES (4, 'developer', 'Usuario de API');
INSERT INTO visit_statuses VALUES (1, 'pending', 'Pendiente');
INSERT INTO visit_statuses VALUES (2, 'process', 'En proceso');
INSERT INTO visit_statuses VALUES (3, 'cancelled', 'Cancelada');
INSERT INTO visit_statuses VALUES (4, 'done', 'Realizada');
INSERT INTO configurations (id, installed) VALUES (1, 0);
